### ISSUE TITLE
Incorrect HttpStatus Code

### ISSUE THREAD

**Issue by dcat23** [Felt-Cute/fantastic-invention-learning-network#7]
In the `GlobalExceptionHandler` for the User management service, the `accessDeniedExceptionHandler` should return a 403 `FORBIDDEN` HttpStatus code but it has a `UNAUTHORIZED` status code

1. Go to users/.../exception/GlobalExceptionHandler
2. Scroll to the `accessDeniedExceptionHandler` method.
3. See the status codes are UNAUTHORIZED

The HttpStatus code for denied access is 403 -  FORBIDDEN by convention.

**Comment by sandymandy12** [comment]
closed with #10
